### ISSUE TITLE
 distribution was not found 

### ISSUE THREAD

**Issue by eminvergil** [autophagy/faereld#2]
Traceback (most recent call last):
  File "/home/emin/.local/bin/faereld", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wisdomhord==0.2.4' distribution was not found and is required by faereld

-----------
faereld insert gives this error . and i installed wisdomhord

**Comment by eminvergil** [comment]
faereld works when i start with sudo:

sudo faereld insert.
