### ISSUE TITLE
No module named 'faereld.summaries'

### ISSUE THREAD

**Issue by bykiandra** [autophagy/faereld#8]
I installed faereld using pip, and I get this error every time I type in the commands `faereld` or `faereld insert`:

```
Traceback (most recent call last):
  File "/Users/kiandra/Library/Python/3.6/bin/faereld", line 6, in <module>
    from faereld.__main__ import main
  File "/Users/kiandra/Library/Python/3.6/lib/python/site-packages/faereld/__main__.py", line 1, in <module>
    from faereld.cli import main
  File "/Users/kiandra/Library/Python/3.6/lib/python/site-packages/faereld/cli.py", line 11, in <module>
    from faereld.controller import Controller
  File "/Users/kiandra/Library/Python/3.6/lib/python/site-packages/faereld/controller.py", line 15, in <module>
    from faereld.db import FaereldData
  File "/Users/kiandra/Library/Python/3.6/lib/python/site-packages/faereld/db.py",line 13, in <module>
    from faereld.summaries.detailed import DetailedAreaSummary, DetailedSummary
ModuleNotFoundError: No module named 'faereld.summaries'
```

**Comment by autophagy** [comment]
@Saoskia Thanks for reporting, I'll look into this. Would you mind telling me what platform/environment youre using Faereld in?

**Comment by autophagy** [comment]
@Saoskia Once again, thank you - I had incorrectly done the packaging/modules for faereld and hadn't noticed since my local environment was installing from source. Fixed the issue, and uploaded a new version. You should be able to access it with ``pip install --upgrade faereld==0.1.1``. If the problem still persists, please feel free to reopen the issue. :slightly_smiling_face:
